# Generated by Django 4.0.3 on 2022-03-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0002_alter_patient_first_name_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='campaign',
            field=models.ManyToManyField(default=1, null=True, to='central_api.missiontrip'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='deleted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.deleted'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientencounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_patient_encounter', to='central_api.patientencounter'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='shared_email_address',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='shared_phone_number',
            field=models.BooleanField(null=True),
        ),
    ]
