# Generated by Django 4.0.1 on 2022-04-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0003_alter_patient_campaign_alter_patient_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='campaign',
            field=models.ManyToManyField(default=1, null=True, to='central_api.MissionTrip'),
        ),
    ]
