# Generated by Django 4.0.1 on 2022-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0004_state_name_alter_patient_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='central_api.Role'),
        ),
    ]
