# Generated by Django 4.0.1 on 2022-05-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0005_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionteam',
            name='mission_trips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.missiontrip'),
        ),
    ]
