# Generated by Django 4.0.1 on 2022-05-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0006_alter_missionteam_mission_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontrip',
            name='user',
            field=models.ManyToManyField(blank=True, to='central_api.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='missionTrips',
            field=models.ManyToManyField(blank=True, related_name='user_mission_trips', to='central_api.MissionTrip'),
        ),
    ]
