# Generated by Django 4.0.1 on 2022-05-15 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0007_alter_missiontrip_user_alter_user_missiontrips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_address', models.CharField(max_length=1024)),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(max_length=1024)),
                ('zip_code', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=1024)),
                ('previous_address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPractitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_id', models.IntegerField(null=True, unique=True)),
                ('campaign_key', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ManagingOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Telecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='tab',
            name='tabFields',
            field=models.ManyToManyField(blank=True, related_name='tab_tab_fields', to='central_api.TabFields'),
        ),
        migrations.AlterField(
            model_name='tabfields',
            name='tab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.tab'),
        ),
        migrations.CreateModel(
            name='HL7FHIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=1024)),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=1024)),
                ('gender', models.CharField(max_length=30)),
                ('birthDate', models.CharField(max_length=64)),
                ('deceasedBoolean', models.BooleanField()),
                ('maritalStatus', models.BooleanField()),
                ('multipleBirthBoolean', models.BooleanField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.address')),
                ('communication', models.ManyToManyField(to='central_api.Communication')),
                ('contact', models.ManyToManyField(to='central_api.Contact')),
                ('generalPractitioner', models.ManyToManyField(to='central_api.GeneralPractitioner')),
                ('identifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.identifier')),
                ('link', models.ManyToManyField(to='central_api.Link')),
                ('managingOrganization', models.ManyToManyField(to='central_api.ManagingOrganization')),
                ('photo', models.ManyToManyField(to='central_api.Photo')),
                ('telecom', models.ManyToManyField(to='central_api.Telecom')),
            ],
        ),
    ]
