# Generated by Django 4.0.1 on 2023-02-01 22:57

import central_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0008_address_communication_generalpractitioner_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='organization',
            field=models.ForeignKey(default=central_api.models.get_test_org, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.organization'),
        ),
    ]
