# Generated by Django 4.1.7 on 2023-03-09 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0009_alter_instance_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder1_office_visit_code', models.JSONField(blank=True, null=True)),
                ('coder1_problem_code', models.JSONField(blank=True, null=True)),
                ('coder1_chief_complaint_code', models.JSONField(blank=True, null=True)),
                ('coder1_covid19_code', models.JSONField(blank=True, null=True)),
                ('coder1_submission_date', models.DateTimeField(null=True)),
                ('coder2_office_visit_code', models.JSONField(blank=True, null=True)),
                ('coder2_problem_code', models.JSONField(blank=True, null=True)),
                ('coder2_chief_complaint_code', models.JSONField(blank=True, null=True)),
                ('coder2_covid19_code', models.JSONField(blank=True, null=True)),
                ('coder2_submission_date', models.DateTimeField(null=True)),
                ('arbiter_office_visit_code', models.JSONField(blank=True, null=True)),
                ('arbiter_problem_code', models.JSONField(blank=True, null=True)),
                ('arbiter_chief_complaint_code', models.JSONField(blank=True, null=True)),
                ('arbiter_covid19_code', models.JSONField(blank=True, null=True)),
                ('arbiter_submission_date', models.DateTimeField(null=True)),
                ('arbiter_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_encounter_arbiter', to='central_api.user')),
                ('coder1_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_encounter_coder1', to='central_api.user')),
                ('coder2_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_encounter_coder2', to='central_api.user')),
                ('patient_encounter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes_patient_encounter', to='central_api.patientencounter')),
            ],
        ),
    ]
