# Generated by Django 4.1.7 on 2023-02-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0009_alter_instance_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientencounter',
            name='arbiter_chief_complaint_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='arbiter_covid19_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='arbiter_office_visit_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='arbiter_problem_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='arbiter_submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='arbiter_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_encounter_arbiter', to='central_api.user'),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder1_chief_complaint_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder1_covid19_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder1_office_visit_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder1_problem_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder1_submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder1_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_encounter_coder1', to='central_api.user'),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder2_chief_complaint_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder2_covid19_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder2_office_visit_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder2_problem_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder2_submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='coder3_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_encounter_coder2', to='central_api.user'),
        ),
        migrations.CreateModel(
            name='PatientMedicalCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coderType', models.TextField()),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.patientencounter')),
            ],
        ),
    ]
