# Generated by Django 4.1.7 on 2023-02-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0010_patientencounter_arbiter_chief_complaint_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientencounter',
            old_name='coder3_user',
            new_name='coder2_user',
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='arbiter_chief_complaint_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='arbiter_covid19_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='arbiter_office_visit_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='arbiter_problem_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='coder1_chief_complaint_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='coder1_covid19_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='coder1_office_visit_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='coder1_problem_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='coder2_chief_complaint_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='coder2_covid19_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='coder2_office_visit_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='coder2_problem_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PatientMedicalCodes',
        ),
    ]
