# Generated by Django 4.1.7 on 2023-03-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0010_medicalcodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcodes',
            old_name='patient_encounter',
            new_name='patientEncounter',
        ),
    ]
