# Generated by Django 4.1.7 on 2023-03-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0011_rename_patient_encounter_medicalcodes_patientencounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcodes',
            name='patientEncounter',
        ),
        migrations.AddField(
            model_name='medicalcodes',
            name='patientncounter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='codes_patient_encounter', to='central_api.patientencounter'),
            preserve_default=False,
        ),
    ]
