# Generated by Django 4.1.7 on 2023-03-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0012_remove_medicalcodes_patientencounter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcodes',
            old_name='patientncounter',
            new_name='patientEncounter',
        ),
    ]
