# Generated by Django 4.1.7 on 2023-03-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0013_rename_patientncounter_medicalcodes_patientencounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcodes',
            name='patientEncounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_patient_encounter', to='central_api.patientencounter', unique=True),
        ),
    ]
