# Generated by Django 4.0.1 on 2023-04-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0011_rename_coder3_user_patientencounter_coder2_user_and_more'),
        ('central_api', '0014_alter_medicalcodes_patientencounter'),
    ]

    operations = [
    ]
