# Generated by Django 4.0.1 on 2023-04-16 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0015_merge_20230416_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientencounter',
            name='arbiter_chief_complaint_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='arbiter_covid19_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='arbiter_office_visit_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='arbiter_problem_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='arbiter_submission_date',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='arbiter_user',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder1_chief_complaint_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder1_covid19_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder1_office_visit_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder1_problem_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder1_submission_date',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder1_user',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder2_chief_complaint_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder2_covid19_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder2_office_visit_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder2_problem_code',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder2_submission_date',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='coder2_user',
        ),
        migrations.AlterField(
            model_name='medicalcodes',
            name='arbiter_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes_arbiter', to='central_api.user'),
        ),
        migrations.AlterField(
            model_name='medicalcodes',
            name='coder1_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes_coder1', to='central_api.user'),
        ),
        migrations.AlterField(
            model_name='medicalcodes',
            name='coder2_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes_coder2', to='central_api.user'),
        ),
        migrations.AlterField(
            model_name='medicalcodes',
            name='patientEncounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_encounter', to='central_api.patientencounter', unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1024, null=True)),
                ('message', models.TextField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='central_api.user')),
            ],
        ),
    ]
