# Generated by Django 4.0.1 on 2023-04-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0016_remove_patientencounter_arbiter_chief_complaint_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
