# Generated by Django 4.1.7 on 2023-05-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0017_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefcomplaint',
            name='patientEncounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.patientencounter'),
        ),
        migrations.AlterField(
            model_name='patientencountertabfields',
            name='patientEncounterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_api.patientencounter', unique=True),
        ),
    ]
