# Generated by Django 4.1.7 on 2023-05-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0018_alter_chiefcomplaint_patientencounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencountertabfields',
            name='patientEncounterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_api.patientencounter'),
        ),
    ]
