# Generated by Django 4.1.7 on 2023-05-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0019_alter_patientencountertabfields_patientencounterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencountertabfields',
            name='tabFieldValue',
            field=models.CharField(max_length=1024),
        ),
    ]
