# Generated by Django 4.1.7 on 2023-05-03 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0020_alter_patientencountertabfields_tabfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofpresentillness',
            name='chief_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_api.chiefcomplaint'),
        ),
        migrations.AlterField(
            model_name='historyofpresentillness',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_api.patientencounter'),
        ),
    ]
