# Generated by Django 4.0.1 on 2023-05-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0021_alter_historyofpresentillness_chief_complaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentStatus',
            fields=[
                ('requestid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('role', models.IntegerField()),
                ('enrollmentstatus', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('organization', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=1024)),
                ('dateCreated', models.DateTimeField()),
            ],
        ),
    ]
