# Generated by Django 4.0.1 on 2023-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0022_enrollmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentstatus',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=30),
        ),
    ]
