# Generated by Django 4.1.7 on 2023-05-30 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0024_alter_patientprescriptions_patientprescriptionreplacements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.patientencounter'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prescriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_api.femruser'),
        ),
    ]
