# Generated by Django 4.0.1 on 2023-06-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0023_enrollmentstatus_phone'),
        ('central_api', '0025_alter_treatment_encounter_alter_treatment_prescriber'),
    ]

    operations = [
    ]
