# Generated by Django 4.0.1 on 2023-06-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0026_merge_20230608_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentstatus',
            name='phone',
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationGenericStrengths',
            field=models.ManyToManyField(null=True, to='central_api.MedicationGenericStrength'),
        ),
        migrations.AlterField(
            model_name='patientprescriptions',
            name='patientPrescriptionReplacements',
            field=models.ManyToManyField(null=True, to='central_api.PatientPrescriptionReplacement'),
        ),
    ]
