# Generated by Django 4.0.1 on 2023-06-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_api', '0027_remove_enrollmentstatus_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentstatus',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=30),
        ),
    ]
